### ISSUE TITLE
Feedback form the Milestone #3 - QA 1

### ISSUE THREAD

**Issue by yoon-bbox** [BalloonBox-Inc/near-oracle-client#31]
### Applicant
- [ ] Coinbase throwing an error on the first attempt.
- [ ] Covalent bug on the first attempt.
- [ ] After selecting “I don’t have a specific amount in mind yet.”, then changing your mind and adjusting the bar, the checkbox keeps being checked. Shouldn’t it uncheck itself unless max? Which amount is being sent to the app? 
- [ ] Fix the speedometer needle issue
- [ ] Display the available loan amount and risk indicator on the score page. (Mike's feedback)

### Provider
- [ ] The amount the user ACTUALLY qualifies for should be displayed below the amount they requested to apply for. Not intuitive for user to have to click on “Explain my score” to see what they qualify for in the text blurb.

### NFT Minting
- [ ] Add a link to redirect to the NEAR wallet collectible tab

### UI Improvement
- [ ] Landing page
- [ ] Learn more page
- [ ] Link to the learn more page on the summary modal
- [ ] Edit some language 
  - In the page where you choose your templates (25-50-100) → replace:
”How much are you looking to borrow?” with
“How much would you like to borrow?”
“$0 ~ $25K” with
“$0 - $25K”
The tilde symbol (~) usually means “approximately”, whereas here we want to indicate a range
“To proceed with the Ethereum wallet, you need to install Metamask browser extension.” with
“To proceed with your Ethereum wallet, you need to install the Metamask browser extension.”
  -  In the page to mint an NFT
center the title, custom attributes, and mint nft   button (see pix above)
replace the title
“Create an NFT” with
“Custom design your NFT”
The word create can be misleading
